services:
  actionservice:
    image: ${DOCKER_REGISTRY-}actionservice
    build:
      context: .
      dockerfile: ActionService/Dockerfile
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
    volumes:
        # before - pgdata:/var/lib/postgresql/data
        - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
        - 27017:27017
    volumes:
        # before - mongodata:/data/db
        - /data/db 
#volumes:
  #pgdata:    
  #mongodata:
  
